//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ES1AutomationEntities : DbContext
    {
        public ES1AutomationEntities()
            : base("name=ES1AutomationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AutomationTask> AutomationTasks { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<SupportedEnvironment> SupportedEnvironments { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<TaskJobMap> TaskJobMaps { get; set; }
        public DbSet<Build> Builds { get; set; }
        public DbSet<TestEnvironment> TestEnvironments { get; set; }
        public DbSet<TestCase> TestCases { get; set; }
        public DbSet<Provider> Providers { get; set; }
        public DbSet<TestCaseExecution> TestCaseExecutions { get; set; }
        public DbSet<AutomationJob> AutomationJobs { get; set; }
        public DbSet<TestResult> TestResults { get; set; }
        public DbSet<ATFConfiguration> ATFConfigurations { get; set; }
        public DbSet<TestSuite> TestSuites { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Ranking> Rankings { get; set; }
        public DbSet<Release> Releases { get; set; }
        public DbSet<Subscriber> Subscribers { get; set; }
        public DbSet<DiagnosticLog> DiagnosticLogs { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectEnvironmentMap> ProjectEnvironmentMaps { get; set; }
    }
}
