//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomationJob
    {
        public AutomationJob()
        {
            this.TaskJobMaps = new HashSet<TaskJobMap>();
            this.TestCaseExecutions = new HashSet<TestCaseExecution>();
        }
    
        public int JobId { get; set; }
        public string Name { get; set; }
        public int Type { get; set; }
        public int Priority { get; set; }
        public int Status { get; set; }
        public int RetryTimes { get; set; }
        public Nullable<int> Timeout { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyBy { get; set; }
        public string Description { get; set; }
        public Nullable<int> TestAgentEnvironmentId { get; set; }
        public Nullable<int> SUTEnvironmentId { get; set; }
    
        public virtual User CreateUser { get; set; }
        public virtual User ModifyUser { get; set; }
        public virtual ICollection<TaskJobMap> TaskJobMaps { get; set; }
        public virtual ICollection<TestCaseExecution> TestCaseExecutions { get; set; }
        public virtual TestEnvironment TestEnvironment_TestAgent { get; set; }
        public virtual TestEnvironment TestEnvironment_SUT { get; set; }
    }
}
