//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomationTask
    {
        public AutomationTask()
        {
            this.TaskJobMaps = new HashSet<TaskJobMap>();
        }
    
        public int TaskId { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public int Priority { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public int ModifyBy { get; set; }
        public int BuildId { get; set; }
        public int EnvironmentId { get; set; }
        public string TestContent { get; set; }
        public string Information { get; set; }
        public string Description { get; set; }
        public Nullable<int> RecurrencePattern { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> WeekDays { get; set; }
        public Nullable<int> WeekInterval { get; set; }
        public Nullable<int> ParentTaskId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ReleaseId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> NotifyStakeholders { get; set; }
        public Nullable<bool> WriteTestResultBack { get; set; }
        public string SetupScript { get; set; }
        public string TeardownScript { get; set; }
        public Nullable<bool> EnableCodeCoverage { get; set; }
    
        public virtual ICollection<TaskJobMap> TaskJobMaps { get; set; }
        public virtual Build Build { get; set; }
        public virtual SupportedEnvironment SupportedEnvironment { get; set; }
        public virtual User CreatedUser { get; set; }
        public virtual User ModifiedUser { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Product Product { get; set; }
        public virtual Release Release { get; set; }
        public virtual Project Project { get; set; }
    }
}
