//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.AutomationTasks = new HashSet<AutomationTask>();
            this.Builds = new HashSet<Build>();
        }
    
        public int BranchId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Path { get; set; }
        public int ProductId { get; set; }
        public int Type { get; set; }
    
        public virtual ICollection<AutomationTask> AutomationTasks { get; set; }
        public virtual ICollection<Build> Builds { get; set; }
        public virtual Product Product { get; set; }
    }
}
