//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnosticLog
    {
        public int LogId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Component { get; set; }
        public Nullable<int> LogType { get; set; }
        public string Message { get; set; }
    }
}
