//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Builds = new HashSet<Build>();
            this.TestCases = new HashSet<TestCase>();
            this.AutomationTasks = new HashSet<AutomationTask>();
            this.Branches = new HashSet<Branch>();
            this.Releases = new HashSet<Release>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> BuildProviderId { get; set; }
        public Nullable<int> TestCaseProviderId { get; set; }
        public Nullable<int> EnvironmentProviderId { get; set; }
        public string RunTime { get; set; }
        public string RQMProjectAlias { get; set; }
    
        public virtual ICollection<Build> Builds { get; set; }
        public virtual ICollection<TestCase> TestCases { get; set; }
        public virtual ICollection<AutomationTask> AutomationTasks { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Provider Provider1 { get; set; }
        public virtual Provider Provider2 { get; set; }
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Release> Releases { get; set; }
    }
}
