//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.AutomationTasks = new HashSet<AutomationTask>();
            this.Subscribers = new HashSet<Subscriber>();
            this.ProjectEnvironmentMaps = new HashSet<ProjectEnvironmentMap>();
        }
    
        public int ProjectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> VCSType { get; set; }
        public string VCSServer { get; set; }
        public string VCSUser { get; set; }
        public string VCSPassword { get; set; }
        public string VCSRootPath { get; set; }
        public string RunTime { get; set; }
    
        public virtual ICollection<AutomationTask> AutomationTasks { get; set; }
        public virtual ICollection<Subscriber> Subscribers { get; set; }
        public virtual ICollection<ProjectEnvironmentMap> ProjectEnvironmentMaps { get; set; }
    }
}
