//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscriber
    {
        public int SubscriberId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Description { get; set; }
        public int SubscriberType { get; set; }
        public int ProjectId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Project Project { get; set; }
    }
}
