//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportedEnvironment
    {
        public SupportedEnvironment()
        {
            this.AutomationTasks = new HashSet<AutomationTask>();
            this.ProjectEnvironmentMaps = new HashSet<ProjectEnvironmentMap>();
        }
    
        public int EnvironmentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string Config { get; set; }
        public int ProviderId { get; set; }
    
        public virtual ICollection<AutomationTask> AutomationTasks { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<ProjectEnvironmentMap> ProjectEnvironmentMaps { get; set; }
    }
}
