//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestEnvironment
    {
        public TestEnvironment()
        {
            this.TestAgent_AutomationJobs = new HashSet<AutomationJob>();
            this.SUT_AutomationJobs = new HashSet<AutomationJob>();
        }
    
        public int EnvironmentId { get; set; }
        public int ProviderId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string Config { get; set; }
        public string Description { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual ICollection<AutomationJob> TestAgent_AutomationJobs { get; set; }
        public virtual ICollection<AutomationJob> SUT_AutomationJobs { get; set; }
    }
}
