//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCase
    {
        public TestCase()
        {
            this.TestCaseExecutions = new HashSet<TestCaseExecution>();
        }
    
        public int TestCaseId { get; set; }
        public int ProviderId { get; set; }
        public string SourceId { get; set; }
        public string Name { get; set; }
        public int ProductId { get; set; }
        public string Feature { get; set; }
        public string ScriptPath { get; set; }
        public int Weight { get; set; }
        public bool IsAutomated { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Ranking { get; set; }
        public string Release { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User CreateUser { get; set; }
        public virtual User ModifyUser { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<TestCaseExecution> TestCaseExecutions { get; set; }
    }
}
