//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCaseExecution
    {
        public TestCaseExecution()
        {
            this.TestResults = new HashSet<TestResult>();
        }
    
        public int ExecutionId { get; set; }
        public int TestCaseId { get; set; }
        public int JobId { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int RetryTimes { get; set; }
        public int Timeout { get; set; }
        public string Info { get; set; }
    
        public virtual TestCase TestCase { get; set; }
        public virtual AutomationJob AutomationJob { get; set; }
        public virtual ICollection<TestResult> TestResults { get; set; }
    }
}
