//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSuite
    {
        public int SuiteId { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string SubSuites { get; set; }
        public string TestCases { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ModityBy { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string SourceId { get; set; }
        public string ExecutionCommand { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual User CreateUser { get; set; }
        public virtual User ModifyUser { get; set; }
    }
}
