//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CreatecTestCases = new HashSet<TestCase>();
            this.ModifiedTestCases = new HashSet<TestCase>();
            this.CreatedAutomationJobs = new HashSet<AutomationJob>();
            this.ModifiedAutomationJobs = new HashSet<AutomationJob>();
            this.TestResults = new HashSet<TestResult>();
            this.CreatedTestSuites = new HashSet<TestSuite>();
            this.ModifiedTestSuites = new HashSet<TestSuite>();
            this.CreatedAutomationTasks = new HashSet<AutomationTask>();
            this.ModifiedAutomationTasks = new HashSet<AutomationTask>();
            this.Subscribers = new HashSet<Subscriber>();
        }
    
        public int UserId { get; set; }
        public int Type { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int Role { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<TestCase> CreatecTestCases { get; set; }
        public virtual ICollection<TestCase> ModifiedTestCases { get; set; }
        public virtual ICollection<AutomationJob> CreatedAutomationJobs { get; set; }
        public virtual ICollection<AutomationJob> ModifiedAutomationJobs { get; set; }
        public virtual ICollection<TestResult> TestResults { get; set; }
        public virtual ICollection<TestSuite> CreatedTestSuites { get; set; }
        public virtual ICollection<TestSuite> ModifiedTestSuites { get; set; }
        public virtual ICollection<AutomationTask> CreatedAutomationTasks { get; set; }
        public virtual ICollection<AutomationTask> ModifiedAutomationTasks { get; set; }
        public virtual ICollection<Subscriber> Subscribers { get; set; }
    }
}
