::===========================================================================================
::
:: Copyright 2013 EMC Corporation.  All rights reserved.  This software 
:: (including documentation) is subject to the terms and conditions set forth 
:: in the end user license agreement or other applicable agreement, and you 
:: may use this software only if you accept all the terms and conditions of 
:: the license agreement.  This software comprises proprietary and confidential 
:: information of EMC.  Unauthorized use, disclosure, and distribution are 
:: strictly prohibited.  Use, duplication, or disclosure of the software and 
:: documentation by the U.S. Government are subject to restrictions set forth 
:: in subparagraph (c)(1)(ii) of the Rights in Technical Data and Computer 
:: Software clause at DFARS 252.227-7013 or subparagraphs (c)(1) and (2) of the 
:: Commercial Computer Software - Restricted Rights at 48 CFR 52.227-19, as 
:: applicable. Manufacturer is EMC Corporation, 176 South St., Hopkinton, MA  01748.
:: 
:: FILE
:: 	Install_Supervisor.bat
::
:: CREATED
::   	5.25.2015
::
:: AUTHOR
::    	Neil Wang
::
:: DESCRIPTION
::   	Silently installs the Supervisor.
::
:: LAST UPDATED 
::   	5.25.2015 Neil Wang
::
:: VERSION	
::	 7.2.0
::
:: USAGE
:: 	SILENT MODE : Command Prompt> Install_Supervisor.bat
::	
::	Arguments can be specified via command line arguments or entered directly
::	within the batch script below.
::
:: ===========================================================================================


::Define variables
SET BATCHLOG="%~1%"
SET INSTALLLOG="%~2%"
SET INSTALLDIR="%~3%"
SET ADDLOCAL="%~4%"

SET SUPERVISOR_SQL_SERVER="%~5%"
SET SUPERVISOR_SQL_DB="%~6%"
SET SUPERVISOR_SQL_AUTH="%~7%"
SET SUPERVISOR_SQL_USER="%~8%"
SET SUPERVISOR_SQL_PASS="%~9%"

shift
shift
shift
shift
shift
shift
shift
shift
shift

SET SUPERVISOR_ACCOUNT_SELECTION="%~1%"
SET SUPERVISOR_ACCOUNT_EXCHANGE_MAPI_PROFILE="%~2%"
SET SUPERVISOR_ACCOUNT_NAME="%~3%"

SET SUPERVISOR_SERVICE_DOMAIN="%~4%"
SET SUPERVISOR_SERVICE_USER="%~5%"
SET SUPERVISOR_SERVICE_PASS="%~6%"

SET SUPERVISOR_WEB_DOMAIN="%~7%"
SET SUPERVISOR_WEB_USER="%~8%"
SET SUPERVISOR_WEB_PASS="%~9%"

shift

SET SUPERVISOR_WEB_SSL="%~1%"
SET DB_DOMAIN="%~2%"
SET DB_USERNAME="%~3%"
SET DB_PASSWORD="%~4%"
SET ES1_EMAIL_ACCOUNT_ADDRESS="%~5%"

CALL %~dp0\DefaultValues.bat

::Set default values
IF %BATCHLOG%=="" 	SET BATCHLOG=%SUPERVISOR_BATCHLOG%
IF %INSTALLLOG%=="" 	SET INSTALLLOG=%SUPERVISOR_INSTALLLOG%
IF %INSTALLDIR%==""	SET INSTALLDIR=%DEFAULT_SUPERVISOR_INSTALLDIR%
IF %ADDLOCAL%==""	SET ADDLOCAL=%DEFAULT_SUPERVISOR_COMPONENTS_TO_INSTALL%

::SQL Information
IF %SUPERVISOR_SQL_SERVER%==""	SET SUPERVISOR_SQL_SERVER=%DEFAULT_EX_SERVER_SQL%
IF %SUPERVISOR_SQL_DB%==""	SET SUPERVISOR_SQL_DB=%DEFAULT_SUPERVISOR_DB_NAME%
IF %SUPERVISOR_SQL_AUTH%==""	SET SUPERVISOR_SQL_AUTH=%DEFAULT_SUPERVISOR_SQL_AUTHENTICATION%
::IF %SUPERVISOR_SQL_USER%==""	SET SUPERVISOR_SQL_USER=%DEFAULT_EX_DOMAIN:"=%\%DEFAULT_EX_USER:"=%
IF %SUPERVISOR_SQL_USER%==""	SET SUPERVISOR_SQL_USER=%DEFAULT_SUPERVISOR_SQL_USER%
IF %SUPERVISOR_SQL_PASS%=="" 	SET SUPERVISOR_SQL_PASS=%DEFAULT_SUPERVISOR_SQL_PASS%

IF %DB_DOMAIN%=="" 	SET DB_DOMAIN=%DEFAULT_EX_DOMAIN%
IF %DB_USERNAME%=="" 	SET DB_USERNAME=%DEFAULT_EX_USER%
IF %DB_PASSWORD%=="" 	SET DB_PASSWORD=%DEFAULT_EX_PASS%
IF %ES1_EMAIL_ACCOUNT_ADDRESS%=="" 	SET ES1_EMAIL_ACCOUNT_ADDRESS=%DEFAULT_ES1_EMAIL_ACCOUNT_ADDRESS%

::Exchange account
IF %SUPERVISOR_ACCOUNT_SELECTION%=="" 	SET SUPERVISOR_ACCOUNT_SELECTION=%DEFAULT_SUPERVISOR_PLATFORM%
IF %SUPERVISOR_ACCOUNT_EXCHANGE_MAPI_PROFILE%=="" 	SET SUPERVISOR_ACCOUNT_EXCHANGE_MAPI_PROFILE=%DEFAULT_SUPERVISOR_EXCHANGE_FROFILE%
IF %SUPERVISOR_ACCOUNT_NAME%=="" 	SET SUPERVISOR_ACCOUNT_NAME=%DEFAULT_SUPERVISOR_EXCHANGE_ACCOUNT%

::Service Information
IF %SUPERVISOR_SERVICE_DOMAIN%==""	SET SUPERVISOR_SERVICE_DOMAIN=%DEFAULT_EX_DOMAIN%
IF %SUPERVISOR_SERVICE_USER%==""	SET SUPERVISOR_SERVICE_USER=%DEFAULT_EX_USER%
IF %SUPERVISOR_SERVICE_PASS%=="" 	SET SUPERVISOR_SERVICE_PASS=%DEFAULT_EX_PASS%

::Web Information
IF %SUPERVISOR_WEB_DOMAIN%==""	SET SUPERVISOR_WEB_DOMAIN=%DEFAULT_EX_DOMAIN%
IF %SUPERVISOR_WEB_USER%==""	SET SUPERVISOR_WEB_USER=%DEFAULT_EX_USER%
IF %SUPERVISOR_WEB_PASS%=="" 	SET SUPERVISOR_WEB_PASS=%DEFAULT_EX_PASS%
IF %SUPERVISOR_WEB_SSL%==""	SET SUPERVISOR_WEB_SSL=%DEFAULT_SUPERVISOR_SSL_ENALBLE%


::Clear Log files
IF EXIST %BATCHLOG% DEL %BATCHLOG%
IF EXIST %INSTALLLOG% DEL %INSTALLLOG%

::Create batch log
ECHO SourceOne Supervisor Install Log >>%BATCHLOG%
ECHO. >>%BATCHLOG%
ECHO INSTALLLOG= %INSTALLLOG% >>%BATCHLOG%
ECHO INSTALLDIR= %INSTALLDIR% >>%BATCHLOG%
ECHO ADDLOCAL= %ADDLOCAL% >>%BATCHLOG%

ECHO SUPERVISOR_SQL_SERVER= %SUPERVISOR_SQL_SERVER% >>%BATCHLOG%
ECHO SUPERVISOR_SQL_DB= %SUPERVISOR_SQL_DB% >>%BATCHLOG%
ECHO SUPERVISOR_SQL_AUTH= %SUPERVISOR_SQL_AUTH% >>%BATCHLOG%
ECHO SUPERVISOR_SQL_USER= %SUPERVISOR_SQL_USER% >>%BATCHLOG%
ECHO SUPERVISOR_SQL_PASS= %SUPERVISOR_SQL_PASS% >>%BATCHLOG%
ECHO DB_DOMAIN= %DB_DOMAIN% >>%BATCHLOG%
ECHO DB_USERNAME= %DB_USERNAME% >>%BATCHLOG%
ECHO DB_PASSWORD= %DB_PASSWORD% >>%BATCHLOG%
ECHO ES1_EMAIL_ACCOUNT_ADDRESS= %ES1_EMAIL_ACCOUNT_ADDRESS% >>%BATCHLOG%

ECHO SUPERVISOR_ACCOUNT_SELECTION= %SUPERVISOR_ACCOUNT_SELECTION% >>%BATCHLOG%
ECHO SUPERVISOR_ACCOUNT_EXCHANGE_MAPI_PROFILE= %SUPERVISOR_ACCOUNT_EXCHANGE_MAPI_PROFILE% >>%BATCHLOG%
ECHO SUPERVISOR_ACCOUNT_NAME= %SUPERVISOR_ACCOUNT_NAME% >>%BATCHLOG%

ECHO SUPERVISOR_SERVICE_DOMAIN= %SUPERVISOR_SERVICE_DOMAIN% >>%BATCHLOG%
ECHO SUPERVISOR_SERVICE_USER= %SUPERVISOR_SERVICE_USER% >>%BATCHLOG%
ECHO SUPERVISOR_SERVICE_PASS= %SUPERVISOR_SERVICE_PASS% >>%BATCHLOG%

ECHO SUPERVISOR_WEB_DOMAIN= %SUPERVISOR_WEB_DOMAIN% >>%BATCHLOG%
ECHO SUPERVISOR_WEB_USER= %SUPERVISOR_WEB_USER% >>%BATCHLOG%
ECHO SUPERVISOR_WEB_PASS= %SUPERVISOR_WEB_PASS% >>%BATCHLOG%
ECHO SUPERVISOR_WEB_SSL= %SUPERVISOR_WEB_SSL% >>%BATCHLOG%

ECHO. >>%BATCHLOG%

::Install Supervisor
@ECHO Installing Supervisor.  Please wait...
ECHO Supervisor Installation >>%BATCHLOG%
ECHO   Started at %DATE% %TIME% >>%BATCHLOG%

ES1_SupervisorSetup.exe /s /v" /qn /L*v %INSTALLLOG% INSTALLDIR=%INSTALLDIR% ADDLOCAL=%ADDLOCAL% IS_SQLSERVER_SERVER=%SUPERVISOR_SQL_SERVER% IS_SQLSERVER_DATABASE=%SUPERVISOR_SQL_DB% IS_SQLSERVER_AUTHENTICATION=%SUPERVISOR_SQL_AUTH% IS_SQLSERVER_USERNAME=%SUPERVISOR_SQL_USER% IS_SQLSERVER_PASSWORD=%SUPERVISOR_SQL_PASS% ES1_EMAIL_ACCOUNT_SELECTION=%SUPERVISOR_ACCOUNT_SELECTION% EXCHANGE_MAPI_PROFILE=%SUPERVISOR_ACCOUNT_EXCHANGE_MAPI_PROFILE% ES1_EMAIL_ACCOUNT_NAME=%SUPERVISOR_ACCOUNT_NAME% ES1_SERVICE_ACCOUNT_DOMAIN=%SUPERVISOR_SERVICE_DOMAIN% ES1_SERVICE_ACCOUNT_USERNAME=%SUPERVISOR_SERVICE_USER% ES1_SERVICE_ACCOUNT_PASSWORD=%SUPERVISOR_SERVICE_PASS% ES1_WEB_ACCOUNT_DOMAIN=%SUPERVISOR_WEB_DOMAIN% ES1_WEB_ACCOUNT_USERNAME=%SUPERVISOR_WEB_USER% ES1_WEB_ACCOUNT_PASSWORD=%SUPERVISOR_WEB_PASS% REQUIRE_SSL=%SUPERVISOR_WEB_SSL% DB_DOMAIN=%DB_DOMAIN% DB_USERNAME=%DB_USERNAME% DB_PASSWORD=%DB_PASSWORD% ES1_EMAIL_ACCOUNT_ADDRESS=%ES1_EMAIL_ACCOUNT_ADDRESS% REBOOT=ReallySuppress "

::Log completion
ECHO   Finished at %DATE% %TIME% >>%BATCHLOG%
ECHO. >>%BATCHLOG%
