//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:42:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class AutomationJobDTO
    {
        [DataMember()]
        public Int32 JobId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int32 Type { get; set; }

        [DataMember()]
        public Int32 Priority { get; set; }

        [DataMember()]
        public Int32 Status { get; set; }

        [DataMember()]
        public Int32 RetryTimes { get; set; }

        [DataMember()]
        public DateTime CreateDate { get; set; }

        [DataMember()]
        public Int32 CreateBy { get; set; }

        [DataMember()]
        public DateTime ModifyDate { get; set; }

        [DataMember()]
        public Int32 ModifyBy { get; set; }

        [DataMember()]
        public Int32 SUTEnvironmentId { get; set; }

        [DataMember()]
        public Int32 TestAgentEnvironmentId { get; set; }

        [DataMember()]
        public Int32 Timeout { get; set; }

        [DataMember()]
        public String Description { get; set; }
      
        public AutomationJobDTO()
        {
        }      
    }
}
