//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:42:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class AutomationTaskDTO
    {
        [DataMember()]
        public Int32 TaskId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int32 Status { get; set; }

        [DataMember()]
        public Int32 Type { get; set; }

        [DataMember()]
        public Int32 Priority { get; set; }

        [DataMember()]
        public DateTime CreateDate { get; set; }

        [DataMember()]
        public Int32 CreateBy { get; set; }

        [DataMember()]
        public DateTime ModifyDate { get; set; }

        [DataMember()]
        public Int32 ModifyBy { get; set; }

        [DataMember()]
        public Int32 BuildId { get; set; }

        [DataMember()]
        public Int32 EnvironmentId { get; set; }

        [DataMember()]
        public string TestContent { get; set; }

        [DataMember()]
        public string Information { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public int RecurrencePattern { get; set; }

        [DataMember()]
        public DateTime StartDate { get; set; }

        [DataMember()]
        public DateTime StartTime { get; set; }

        [DataMember()]
        public int WeekDays { get; set; }

        [DataMember()]
        public int WeekInterval { get; set; }

        [DataMember()]
        public Int32 ParentTaskId;

        [DataMember()]
        public Int32 BranchId;

        [DataMember()]
        public Int32 ReleaseId;

        [DataMember()]
        public Int32 ProductId;       

        [DataMember()]
        public Int32 ProjectId;

        [DataMember()]
        public bool WriteTestResultBack;

        [DataMember()]
        public bool NotifyStakeholders;

        [DataMember()]
        public string SetupScript;

        [DataMember()]
        public string TeardownScript;

        [DataMember()]
        public bool EnableCodeCoverage;

        public AutomationTaskDTO()
        {
        } 
    }

    [DataContract()]
    public class AutomationRunningStatusDTO
    {
        [DataMember()]
        public Int32 TaskId { get; set; }

        [DataMember()]
        public Int32 Status { get; set; }

        [DataMember()]
        public Int32 ExecutionPercentage { get; set; }

        [DataMember()]
        public String Information { get; set; }

        [DataMember()]
        public String TestCasesExecutionStatusList { get; set; }

        [DataMember()]
        public String TestCasesExecutionStatusCountList { get; set; }

        public AutomationRunningStatusDTO()
        { }
    }
}
