//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:42:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class ProductDTO
    {
        [DataMember()]
        public Int32 ProductId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 BuildProviderId { get; set; }

        [DataMember()]
        public Int32 TestCaseProviderId { get; set; }

        [DataMember()]
        public Int32 EnvironmentProviderId { get; set; }

        [DataMember()]
        public string RunTime { get; set; }

        [DataMember()]
        public string RQMProjectAlias { get; set; }


        public ProductDTO()
        {
        }

    }
}
