//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:43:01
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class ProviderDTO
    {
        [DataMember()]
        public Int32 ProviderId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int32 Category { get; set; }

        [DataMember()]
        public String Type { get; set; }

        [DataMember()]
        public String Path { get; set; }

        [DataMember()]
        public String Config { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        public ProviderDTO()
        {
        }
    }
}
