//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:42:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class SupportedEnvironmentDTO
    {
        [DataMember()]
        public Int32 EnvironmentId { get; set; }

        [DataMember()]
        public String Name { get; set; }
        [DataMember()]
        public Int32 ProviderId { get; set; }

        
        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Config { get; set; }

        public SupportedEnvironmentDTO()
        {
        }     
    }
}
