//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:42:58
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class TaskJobMapDTO
    {
        [DataMember()]
        public Int32 MapId { get; set; }

        [DataMember()]
        public Int32 TaskId { get; set; }

        [DataMember()]
        public Int32 JobId { get; set; }

        public TaskJobMapDTO()
        {
        }      
    }
}
