//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:43:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class TestCaseExecutionDTO
    {
        [DataMember()]
        public Int32 ExecutionId { get; set; }

        [DataMember()]
        public Int32 TestCaseId { get; set; }

        [DataMember()]
        public Int32 JobId { get; set; }

        [DataMember()]
        public Int32 Status { get; set; }

        [DataMember()]
        public String StartTime { get; set; }

        [DataMember()]
        public String EndTime { get; set; }

        [DataMember()]
        public Int32 RetryTimes { get; set; }

        [DataMember()]
        public string Info { get; set; }

        public TestCaseExecutionDTO()
        {
        }       
    }
}
