//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:43:03
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class TestResultDTO
    {
        [DataMember()]
        public Int32 ResultId { get; set; }

        [DataMember()]
        public Int32 ExecutionId { get; set; }

        [DataMember()]
        public Int32 Result { get; set; }

        [DataMember()]
        public Boolean IsTriaged { get; set; }

        [DataMember()]
        public Nullable<Int32> TriagedBy { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Files { get; set; }

        public TestResultDTO()
        {
        }       
    }

    [DataContract()]
    public partial class HistoricalTestResultsDTO
    {
        [DataMember()]
        public Int32 TestCaseId { get; set; }

        [DataMember()]
        public string TestCaseName { get; set; }

        [DataMember()]
        public Int32 TaskId { get; set; }

        [DataMember()]
        public string TaskName { get; set; }

        [DataMember()]
        public Int32 BuildId { get; set; }
                
        [DataMember()]
        public string BuildName { get; set; }

        [DataMember()]
        public Int32 ResultId { get; set; }

        [DataMember()]
        public Int32 Result { get; set; }

        [DataMember()]
        public string ResultComments { get; set; }

        public HistoricalTestResultsDTO()
        {
        }
    }
}
