//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:43:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class TestCaseDTO
    {
        [DataMember()]
        public Int32 TestCaseId { get; set; }

        [DataMember()]
        public String SourceId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public Int32 ProductId { get; set; }

        [DataMember()]
        public String Feature { get; set; }

        [DataMember()]
        public String ScriptPath { get; set; }

        [DataMember()]
        public string Ranking { get; set; }

        [DataMember()]
        public string Release { get; set; }

        [DataMember()]
        public Int32 Weight { get; set; }

        [DataMember()]
        public Boolean IsAutomated { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> ModifyBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifyTime { get; set; }

        [DataMember()]
        public String Description { get; set; }
      
        public TestCaseDTO()
        {
        }     
    }
}
