//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:43:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class TestSuiteDTO
    {
        [DataMember()]
        public Int32 SuiteId { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String SubSuites { get; set; }

        [DataMember()]
        public String TestCases { get; set; }

        [DataMember()]
        public Nullable<Int32> CreateBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreateTime { get; set; }

        [DataMember()]
        public Nullable<Int32> ModityBy { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifyTime { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 Type { get; set; }

        [DataMember()]
        public String ExecutionCommand { get; set; }

        public TestSuiteDTO()
        {
        }
    }
}
