//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2013/11/26 - 10:42:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace Core.DTO
{
    [DataContract()]
    public partial class UserDTO
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public Int32 Type { get; set; }

        [DataMember()]
        public String Username { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Int32 Role { get; set; }

        [DataMember()]
        public Boolean IsActive { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public String Email { get; set; }


        public UserDTO()
        {
        }

    
    }
}
